### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by dm82m** [mcarlucci/decky-storage-cleaner#9] opened 2024-02-05 15:29 UTC
![image](https://github.com/mcarlucci/decky-storage-cleaner/assets/736311/ba776f80-6448-4fd3-935e-28e7427d89f9)

current steam deck beta and decky pre release.

solution could be taken from https://github.com/jurassicplayer/decky-autoflatpaks/issues/14

**Comment by 18209550** [comment] 2024-02-07 01:58
this was fixed. try updating autoflatpaks

**Comment by dm82m** [comment] 2024-02-07 05:54
It was fixed for auto flatpaks but not for storage cleaner. Storage cleaner is still broken.

**Comment by martpendle** [comment] 2024-02-07 15:38
Same issue here on is 3.5.14 and the latest stem client beta. It appears to also affect the wine cellar plugin so I’m guessing valve changed their API (or something similar) and plugins need an update to handle the change

**Comment by martpendle** [comment] 2024-02-12 13:37
@mcarlucci please see this comment from the wine cellar plugin on what the root cause of this issue is - https://github.com/FlashyReese/decky-wine-cellar/issues/10#issuecomment-1938688965

**Comment by martpendle** [comment] 2024-02-17 09:31
This appears to be resolved in the latest plugin update (decky pre release and plugin testing store)

**Closed** 2024-02-17 09:57 UTC
